# Generated by Django 6.0.1 on 2026-09-20 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('snapshot_name', models.CharField(max_length=255)),
                ('snapshot_language', models.CharField(default='html', max_length=50)),
                ('snapshot_files', models.JSONField(default=list)),
                ('author_username', models.CharField(max_length=150)),
                ('is_public', models.BooleanField(default=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='projects.project')),
            ],
        ),
    ]
