# Generated by Django 6.0.1 on 2026-09-22 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='language',
            field=models.CharField(choices=[('html', 'HTML'), ('c', 'C'), ('java', 'Java')], default='html', max_length=50),
        ),
    ]
