# Generated by Django 6.0.1 on 2026-09-25 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='challenge',
            old_name='test_cases',
            new_name='validation_rules',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='solution',
        ),
        migrations.AddField(
            model_name='challenge',
            name='category',
            field=models.CharField(choices=[('html', 'HTML'), ('css', 'CSS'), ('layout', 'Layout'), ('forms', 'Forms'), ('cards', 'Cards')], default='html', max_length=30),
        ),
        migrations.AddField(
            model_name='challengeattempt',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='difficulty',
            field=models.CharField(choices=[('Beginner', 'Beginner 🌱'), ('Easy', 'Easy ⭐'), ('Intermediate', 'Intermediate ⭐⭐')], default='Beginner', max_length=20),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='language',
            field=models.CharField(default='html', max_length=50),
        ),
        migrations.CreateModel(
            name='ChallengeProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passed', models.BooleanField(default=False)),
                ('best_score', models.IntegerField(default=0)),
                ('total_requirements', models.IntegerField(default=0)),
                ('last_code', models.TextField(blank=True, default='')),
                ('passed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='challenges.challenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'challenge')},
            },
        ),
    ]
