# Generated by Django 6.0.1 on 2026-09-20 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('track', models.CharField(choices=[('html', 'HTML Foundations'), ('css', 'Styling with CSS'), ('javascript', 'JavaScript Magic'), ('python', 'Python Adventure')], max_length=50)),
                ('order', models.PositiveIntegerField(default=1)),
                ('concept', models.CharField(max_length=255)),
                ('explanation', models.TextField()),
                ('starter_code', models.TextField(blank=True, default='')),
                ('hint', models.TextField(blank=True, default='')),
                ('solution', models.TextField(blank=True, default='')),
                ('expected_output', models.TextField(blank=True, default='')),
                ('xp_reward', models.PositiveIntegerField(default=25)),
            ],
            options={
                'ordering': ['track', 'order'],
            },
        ),
        migrations.CreateModel(
            name='UserLessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='learning.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'lesson')},
            },
        ),
    ]
